Add `--base-url` option to `aio app init --repo`
adobe/aio-cli-plugin-app pull request #822
Opened 2024-11-29 22:59 UTC by obarcelonap

## Description

Implements https://github.com/adobe/aio-cli/issues/695

## Related Issue

## Motivation and Context

In order to be able to use quickstarts in Github's Enterprise Server.

## How Has This Been Tested?

Unit testing

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ x ] My code follows the code style of this project.
- [ x ] My change requires a change to the documentation.
- [ x ] I have updated the documentation accordingly.
- [ x ] I have read the **CONTRIBUTING** document.
- [ x ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.

2024-12-02 13:45 UTC, shazron requested changes

2024-12-02 14:53 UTC, obarcelonap commented on README.md
> +    [--base-url <value> ] [--linter none|basic|adobe-recommended]
done

2024-12-02 22:43 UTC, purplecabbage commented
This looks good, however, I would prefer it be done without an additional flag.
The current implementation mimics `npm install [<package-spec> ...]` in the way it interprets the package-spec
For example:
1. install an npm published + scoped package ( plus version options )
    npm i @adobe/aio-lib-state
2. install from github user/repo ( plus numerous branch options )
    npm i adobe/aio-lib-state
3. install from url (ssh)
    npm i git@github.com:adobe/aio-lib-state.git
4. install from url (https)
    npm i git@github.com:adobe/aio-lib-state.git

I think we should similarly overload the --repo flag to support these cases.

2024-12-03 14:53 UTC, obarcelonap commented
@purplecabbage thanks for your feedback. I am not sure if we can mimic npm's behaviour since the repo option allows to specify directories.

In regards your examples:
opt 1 is out of the scope, because quickstarts are not published in any artifact repository
opt 2 is what is currently implemented
opt 3 and 4 would be feasible but from my perspective it would give the false impression that the plugin is using git clone command which is not. Actually I am not sure how we will reflect the subfolder in the repo for these cases.

I would not overcomplicate the implementation. This pull request seems a quick win for me to support github enterprise installation. While I agree your proposal is much nicer I believe it requires a redesign of the command specification which I am not sure if is worthy.

2024-12-04 05:40 UTC, obarcelonap commented
@shazron @purplecabbage can I get your feedback based on my last comment?

If still is desired to use the npm approach, I was wondering how a concrete example would look like.
```
# prefix with github enterprise server url
aio app init --repo mygithub.com:myorg/myrepo/myfolder

# by default uses github (current behaviour)
aio app init --repo adobe/appbuilder-quickstarts/dne 
```
Is that sufficient from your perspective?

2026-08-06 15:51 UTC, obarcelonap commented
closing since this is pretty outdated

2026-08-06 15:51 UTC, closed without merging